--- Makefile    2023-01-25 12:10:31
+++ Makefile    2023-01-25 12:12:39
@@ -121,21 +121,20 @@
 source:
     rm -rf $(source_build_directory)
     mkdir -p $(source_build_directory)
-    tar cvzf $(source_package_name).tar.gz ../$(app_name) \
-    --exclude-vcs \
+    tar --exclude-vcs \
     --exclude="../$(app_name)/build" \
     --exclude="../$(app_name)/js/node_modules" \
     --exclude="../$(app_name)/node_modules" \
     --exclude="../$(app_name)/*.log" \
     --exclude="../$(app_name)/js/*.log" \
+    -cvzf $(source_package_name).tar.gz ../$(app_name)

 # Builds the source package for the app store, ignores php and js tests
 .PHONY: appstore
 appstore:
     rm -rf $(appstore_build_directory)
     mkdir -p $(appstore_build_directory)
-    tar cvzf $(appstore_package_name).tar.gz ../$(app_name)
-    --exclude="../$(app_name)/build" \
+    tar --exclude="../$(app_name)/build" \
     --exclude="../$(app_name)/tests" \
     --exclude="../$(app_name)/Makefile" \
     --exclude="../$(app_name)/*.log" \
@@ -156,6 +155,7 @@
     --exclude="../$(app_name)/.*" \
     --exclude="../$(app_name)/js/.*" \
     --exclude-vcs \
+    -cvzf $(appstore_package_name).tar.gz ../$(app_name)

 .PHONY: coverage
 coverage:

